### ISSUE TITLE
Implémenter le xPost

### ISSUE THREAD

**Issue by devnewton** [sveetch/djangotribune#21]
Cf zorel/olccs-rails#3

**Comment by sveetch** [comment]
En résumé ça consiste à implémenter l'utilisation de l'argument du last_id dans la requête POST lors du post d'un message et que le remote qui répond utilise l'argument pour la construction du backend en réponse.

Par contre, je conserve l'utilisation du nom d'argument `last_id` par cohérence (et non `last` ou `id` comme le mentionne zorel/olccs-rails#3)

**Comment by sveetch** [comment]
Ok c'est fait dans la version 0.7.7 (commit 9da86ba).
