### ISSUE TITLE
Djangotribune dependencies

### ISSUE THREAD

**Issue by mhb11** [sveetch/djangotribune#22]
@sveetch: I want to use djangotribune as a chatting feature for a web app I'm building. Mine is a project for developing countries - some of the devices people use to get online are downright ancient (e.g. internet-enabled feature phones). Thus all in all, my bottleneck is that I can't use any tech for my web app that relies on:

JavaScript
SVG images and WOFF font types
HTTPS support
iframes
Video and large images
Flash and Java applets

Cursory look at djangotribune seems it can work in the absence of the aforementioned. Can you confirm that, so I go ahead and start integrating this in my system?

**Comment by sveetch** [comment]
The only thing from your excluded techs that djangotribune use is Javascript.

There is a view that works without Javascript : https://github.com/sveetch/djangotribune/blob/master/djangotribune/urls.py#L19

But this is much more a fallback view, historically created for old phones (not smartphone) or commandline browser like Links2. From my point of view, probably 60% of djangotribune interest resides in the frontend interface using Javascript.

**Comment by mhb11** [comment]
Thanks @sveetch Old phones are precisely my target demographic. I'm working on an initiative to develop basic internet applications for people from 3rd world economies who have never (or seldom) used the Internet before. There are 160 million such people in my country alone (and more than a billion in my neighboring country). Around 20% of them is my total addressable market. I'm slowly, steadily looking to build up toward that.

Having a chatting app for them is going to be very beneficial. I've looked at other Django projects and all seem to be tightly coupled to Javascript. At least you support a view for old phones, so I'll go with your code.

Any special instructions for me as I integrate your app?

**Comment by sveetch** [comment]
You probably would have to mount your own urls.py to make the noscript version as the default view, because actually this the "javascript version".

Note that html is builded on HTML5 and css is CSS3, so it may break most of browser for old mobile phones (like GSM and older).

**Comment by mhb11** [comment]
Thanks for the heads up dude. I'll dive in, and do my best to make this work. I'll share how my journey goes with you, hopefully I can get a working product out! 

Thanks again for replying!
